version: '3'
services:
  s1:
    build:
      context: ./s1/
      dockerfile: Dockerfile 
    ports:
      - "8081:8081"
  s2:
    build:
      context: ./s2/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - mynetwork
  s3:
    build:
      context: ./s3/
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - mynetwork
    environment:

     #via extrnal host nw
      S1_URL: "http://172.22.96.1:8081/add"  # Use the service name as the hostname
      S2_URL: "http://172.22.96.1:8082/sub"  # Use the service name as the hostname
      

      # via docker network
      #S1_URL: "http://s1:8081/add"  # Use the service name as the hostname
      #S2_URL: "http://s2:8082/sub"  # Use the service name as the hostname

networks:
  mynetwork:
